//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG.SharePoint.Test.WebParts.BGWebPart {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class BGWebPart {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "15.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(BGWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControl__control2() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            @__ctrl.Language = "javascript";
            @__ctrl.Name = "/_layouts/15/BG.SharePoint.Test/JS/modal-dialog.js";
            @__ctrl.OnDemand = false;
            @__ctrl.Localizable = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void @__BuildControlTree(global::BG.SharePoint.Test.WebParts.BGWebPart.BGWebPart @__ctrl) {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control2();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<div>\r\n    <input id=\"test-input\"/>\r\n</div>\r\n<br />\r\n<div>\r\n    <button type=" +
                        "\"button\" id=\"test-button\" onclick=\"testcall()\">Жми! Тест</button>\r\n</div>\r\n<labe" +
                        "l id=\"test-result\"></label>\r\n<br />\r\n\r\n<div>\r\n    <button type=\"button\" id=\"crea" +
                        "te-button\" onclick=\"showDialog()\">Создать записи!</button>   \r\n</div>\r\n\r\n <div s" +
                        "tyle=\"display:none\">\r\n\r\n        <div id=\"modal-dialog\">\r\n        \r\n            <" +
                        "table>\r\n                <tr>\r\n                    <td>\r\n                        " +
                        "<label>Наименование</label>\r\n                    </td> \r\n                    <td" +
                        ">\r\n                        <input id=\"naim\" type=\"text\" required>\r\n             " +
                        "           <p style=\"color:red\" id=\"naim-message\"></p>\r\n                    </td" +
                        "> \r\n                </tr>\r\n\r\n                <tr>\r\n                    <td>\r\n   " +
                        "                     <label>Номер начальный</label>\r\n                    </td> \r" +
                        "\n                    <td>\r\n                        <input id=\"firstnumber\" type=" +
                        "\"number\" min=\"1\" required> \r\n                        <p style=\"color:red\" id=\"fi" +
                        "rstnumber-message\"></p>\r\n                    </td> \r\n                </tr>\r\n\r\n  " +
                        "              <tr>\r\n                    <td>\r\n                        <label>Ном" +
                        "ер конечный</label>\r\n                    </td> \r\n                    <td>\r\n     " +
                        "                   <input id=\"lastnumber\" type=\"number\" min=\"1\"  required>\r\n    " +
                        "                    <p style=\"color:red\" id=\"lastnumber-message\"></p>\r\n         " +
                        "           </td> \r\n                </tr>\r\n\r\n                <tr>\r\n              " +
                        "      <td>\r\n                        <label>Цвет</label>\r\n                    </t" +
                        "d> \r\n                    <td>\r\n                        <select id=\"test-color\" n" +
                        "ame=\"color\">\r\n                        </select>\r\n                    </td> \r\n   " +
                        "                 <td>\r\n                        <input id=\"newcolor\" type=\"text\">" +
                        "   \r\n                    </td> \r\n                    <td>\r\n                     " +
                        "    <button onclick=\"createNewColor()\">Новый цвет</button>  \r\n                  " +
                        "  </td> \r\n                </tr>\r\n\r\n            </table>             \r\n          " +
                        "  \r\n            <button onclick=\"createListItem()\">Записать</button>\r\n          " +
                        "  <button>Отменить</button>\r\n            \r\n            </div>\r\n     \r\n </div>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
